name: Build Windows Packages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_package-windows-reusable.yml
    with:
      app-name: DailyPlants
      project-file: src/DailyPlants/DailyPlants.csproj
      project-path: src/DailyPlants
      windows-target-framework: net10.0-windows10.0.26100
      executable-name: DailyPlants.exe
      submit-to-store: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets: inherit
